WORDPRESS_DB_USER=wp_scratch
WORDPRESS_DB_NAME=wp_scratch
WORDPRESS_DB_PASSWORD=wp_scratch
# APACHE_RUN_USER=www-data
# APACHE_RUN_GROUP=www-data
IMPORT_SRC=~/tmp/wp-import/
IMPORT_SQL=${IMPORT_SRC}/wordpress.sql
EXTRACT_DIR=./scratch
SRC_DIR=./
